import { db } from './db'
import { projectsTable } from '../../src/infrastructure/db/schema'

const projects = [
  {
    title: 'OctoSight',
    slug: 'octosight',
    descriptionShort: 'End-to-end anti-phishing & fraud detection prototype for digital banking',
    thumbnailUrl: null,
    techStacks: ['FastAPI', 'Next.js', 'Python', 'TypeScript', 'Docker', 'MySQL', 'scikit-learn'],
    isFeatured: true,
    category: 'Web App',
    githubUrl: 'https://github.com/G4l1le30/octosight-web-app',
    liveUrl: 'https://octosight.vercel.app/',
    additionalLinks: null,
    sortOrder: 1,
  },
  {
    title: 'NeuroClash GG',
    slug: 'neuroclash-gg',
    descriptionShort: 'AI-powered edutainment platform with auto-battler quiz mechanics',
    thumbnailUrl: null,
    techStacks: ['Next.js', 'TypeScript', 'Supabase', 'Zustand', 'Gemini API', 'Tailwind CSS'],
    isFeatured: true,
    category: 'Web App',
    githubUrl: 'https://github.com/mrobialwww/neuroclash-gg',
    liveUrl: 'https://neuroclash-gg.vercel.app/',
    additionalLinks: null,
    sortOrder: 2,
  },
  {
    title: 'Raion Web',
    slug: 'raion-web',
    descriptionShort: 'Official website for Raion Community with CMS and Form Management System',
    thumbnailUrl: null,
    techStacks: ['Next.js', 'TypeScript', 'Supabase', 'Drizzle ORM', 'Tailwind CSS', 'Radix UI'],
    isFeatured: true,
    category: 'Web App',
    githubUrl: 'https://github.com/Raion-Community/raion-web-migrate',
    liveUrl: 'https://raion-web.vercel.app/',
    additionalLinks: null,
    sortOrder: 3,
  },
  {
    title: 'LWU',
    slug: 'lwu',
    descriptionShort: 'Modern online English education platform with premium design',
    thumbnailUrl: null,
    techStacks: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Radix UI'],
    isFeatured: true,
    category: 'Web App',
    githubUrl: 'https://github.com/rhesatsaqif23/lwu-website',
    liveUrl: 'https://lwu-id.vercel.app/',
    additionalLinks: null,
    sortOrder: 4,
  },
  {
    title: 'GameVault',
    slug: 'gamevault',
    descriptionShort: 'Game catalog platform for Indonesian gamer community',
    thumbnailUrl: null,
    techStacks: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Vitest'],
    isFeatured: false,
    category: 'Web App',
    githubUrl: 'https://github.com/rhesatsaqif23/GameVault',
    liveUrl: 'https://gamevault-gamerverse.vercel.app/',
    additionalLinks: null,
    sortOrder: 5,
  },
  {
    title: 'Votely',
    slug: 'votely',
    descriptionShort: 'Web-based multi-voting platform with CI/CD pipeline and Jenkins',
    thumbnailUrl: null,
    techStacks: ['Flask', 'React', 'Python', 'Docker', 'Jenkins', 'SQLite'],
    isFeatured: false,
    category: 'Web App',
    githubUrl: 'https://github.com/SakaGintoki/CI-CD',
    liveUrl: null,
    additionalLinks: null,
    sortOrder: 6,
  },
  {
    title: 'JW-Talk',
    slug: 'jw-talk',
    descriptionShort: 'Real-time secure group chat with JWT auth and WebSocket messaging',
    thumbnailUrl: null,
    techStacks: ['Next.js', 'Express', 'TypeScript', 'Socket.io', 'Prisma', 'PostgreSQL'],
    isFeatured: false,
    category: 'Web App',
    githubUrl: 'https://github.com/rhesatsaqif23/jw-talk',
    liveUrl: 'https://jw-talk.vercel.app/',
    additionalLinks: null,
    sortOrder: 7,
  },
  {
    title: 'ZenPilates',
    slug: 'zenpilates',
    descriptionShort: 'Full-stack Pilates studio reservation system',
    thumbnailUrl: null,
    techStacks: ['Next.js', 'Golang', 'Supabase', 'Midtrans', 'PostgreSQL'],
    isFeatured: false,
    category: 'Web App',
    githubUrl: 'https://github.com/rhesatsaqif23/diro-reservation-app',
    liveUrl: 'https://zenpilates-web.vercel.app/',
    additionalLinks: null,
    sortOrder: 8,
  },
  {
    title: 'Immunify',
    slug: 'immunify',
    descriptionShort: 'Mobile app for managing children\'s vaccination schedules',
    thumbnailUrl: null,
    techStacks: ['Kotlin', 'Jetpack Compose', 'MVVM', 'OpenStreetMap', 'Fused Location Provider'],
    isFeatured: false,
    category: 'Mobile App',
    githubUrl: 'https://github.com/gitaufar/immunify-PAPB-',
    liveUrl: null,
    additionalLinks: null,
    sortOrder: 9,
  },
  {
    title: 'EduEarth',
    slug: 'eduearth',
    descriptionShort: 'Interactive 3D Earth Layer Visualization',
    thumbnailUrl: null,
    techStacks: ['Three.js', 'JavaScript', 'WebGL'],
    isFeatured: false,
    category: 'Web App',
    githubUrl: 'https://github.com/gabasRya/komfis',
    liveUrl: 'https://eduearth-komgraf.vercel.app/',
    additionalLinks: null,
    sortOrder: 10,
  },
  {
    title: 'KameraKu',
    slug: 'kameraku',
    descriptionShort: 'Camera application built with Jetpack Compose and CameraX',
    thumbnailUrl: null,
    techStacks: ['Kotlin', 'Jetpack Compose', 'CameraX'],
    isFeatured: false,
    category: 'Mobile App',
    githubUrl: 'https://github.com/rhesatsaqif23/KameraKu',
    liveUrl: null,
    additionalLinks: null,
    sortOrder: 11,
  },
  {
    title: 'OptiFind',
    slug: 'optifind',
    descriptionShort: 'Web-based Lost and Found platform — Top 5 Finalist at IT FEST UMK',
    thumbnailUrl: null,
    techStacks: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS'],
    isFeatured: true,
    category: 'Web App',
    githubUrl: 'https://github.com/dafialmadinah/OptiFind',
    liveUrl: 'https://opti-find-bogh.vercel.app/',
    additionalLinks: null,
    sortOrder: 12,
  },
  {
    title: 'HearMe',
    slug: 'hearme',
    descriptionShort: 'Voice-based stress detection for student mental health awareness',
    thumbnailUrl: null,
    techStacks: ['Kotlin', 'Jetpack Compose', 'Firebase', 'Gemini API', 'FastAPI'],
    isFeatured: false,
    category: 'Mobile App',
    githubUrl: 'https://github.com/rhesatsaqif23/hear-me-app',
    liveUrl: null,
    additionalLinks: null,
    sortOrder: 13,
  },
  {
    title: 'Zelow',
    slug: 'zelow',
    descriptionShort: 'Food waste reduction platform connecting UMKM with consumers',
    thumbnailUrl: null,
    techStacks: ['Flutter', 'Dart', 'Firebase'],
    isFeatured: false,
    category: 'Mobile App',
    githubUrl: 'https://github.com/Raion-App-Programmer/ZELOW',
    liveUrl: null,
    additionalLinks: null,
    sortOrder: 14,
  },
  {
    title: 'Swara Ibu',
    slug: 'swara-ibu',
    descriptionShort: 'Voice-based emotional analysis for postpartum depression support — 1st Place',
    thumbnailUrl: null,
    techStacks: ['Kotlin', 'Jetpack Compose', 'Firebase', 'Gemini API', 'FastAPI', 'OpenAI Whisper', 'Librosa'],
    isFeatured: true,
    category: 'Mobile App',
    githubUrl: 'https://github.com/gitaufar/swaraibu-app',
    liveUrl: null,
    additionalLinks: null,
    sortOrder: 15,
  },
  {
    title: 'SABI',
    slug: 'sabi',
    descriptionShort: 'Waste management app with reward points system',
    thumbnailUrl: null,
    techStacks: ['Kotlin', 'Jetpack Compose', 'Firebase', 'UploadCare'],
    isFeatured: true,
    category: 'Mobile App',
    githubUrl: 'https://github.com/muktiabdii/sabi-app',
    liveUrl: null,
    additionalLinks: null,
    sortOrder: 16,
  },
  {
    title: 'Found It!',
    slug: 'found-it',
    descriptionShort: 'Web-based Lost and Found for campus environment (Laravel)',
    thumbnailUrl: null,
    techStacks: ['Laravel', 'PHP', 'MySQL', 'Bootstrap'],
    isFeatured: false,
    category: 'Web App',
    githubUrl: 'https://github.com/rhesatsaqif23/Found_It_Web',
    liveUrl: null,
    additionalLinks: null,
    sortOrder: 17,
  },
  {
    title: 'Eventpal',
    slug: 'eventpal',
    descriptionShort: 'Mobile app for event vendors discovery and booking',
    thumbnailUrl: null,
    techStacks: ['Kotlin', 'XML', 'Firebase'],
    isFeatured: false,
    category: 'Mobile App',
    githubUrl: 'https://github.com/rhesatsaqif23/Eventpal',
    liveUrl: null,
    additionalLinks: null,
    sortOrder: 18,
  },
]

export async function seedProjects() {
  console.log('Seeding projects...')
  await db.delete(projectsTable)
  for (const project of projects) {
    await db.insert(projectsTable).values(project)
    console.log(`  ✓ ${project.title}`)
  }
  console.log(`  → ${projects.length} projects inserted\n`)
}
