/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSsoCallbackRouteImport } from './routes/auth/sso-callback'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminSkillsRouteImport } from './routes/admin/skills'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminExperiencesRouteImport } from './routes/admin/experiences'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCaseStudiesRouteImport } from './routes/admin/case-studies'
import { Route as AdminAchievementsRouteImport } from './routes/admin/achievements'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/auth/sso-callback',
  path: '/auth/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExperiencesRoute = AdminExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCaseStudiesRoute = AdminCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/case-studies': typeof AdminCaseStudiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sso-callback': typeof AuthSsoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/case-studies': typeof AdminCaseStudiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sso-callback': typeof AuthSsoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/case-studies': typeof AdminCaseStudiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sso-callback': typeof AuthSsoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/admin/achievements'
    | '/admin/case-studies'
    | '/admin/dashboard'
    | '/admin/experiences'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/skills'
    | '/admin/stats'
    | '/auth/sign-in'
    | '/auth/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/admin/achievements'
    | '/admin/case-studies'
    | '/admin/dashboard'
    | '/admin/experiences'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/skills'
    | '/admin/stats'
    | '/auth/sign-in'
    | '/auth/sso-callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/admin/achievements'
    | '/admin/case-studies'
    | '/admin/dashboard'
    | '/admin/experiences'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/skills'
    | '/admin/stats'
    | '/auth/sign-in'
    | '/auth/sso-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso-callback': {
      id: '/auth/sso-callback'
      path: '/auth/sso-callback'
      fullPath: '/auth/sso-callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/experiences': {
      id: '/admin/experiences'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof AdminExperiencesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/case-studies': {
      id: '/admin/case-studies'
      path: '/case-studies'
      fullPath: '/admin/case-studies'
      preLoaderRoute: typeof AdminCaseStudiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminCaseStudiesRoute: typeof AdminCaseStudiesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExperiencesRoute: typeof AdminExperiencesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminStatsRoute: typeof AdminStatsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminCaseStudiesRoute: AdminCaseStudiesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExperiencesRoute: AdminExperiencesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminStatsRoute: AdminStatsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
